# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')
# code only work with libray version: scikit-learn==0.24 and imbalanced-learn==0.8.1

In [2]:
import sklearn
print(sklearn.__version__)

0.24.0

In [3]:
import imblearn
print(imblearn.__version__)

0.8.1

In [4]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [5]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.preprocessing import LabelEncoder

## Read the CSV and Perform Basic Data Cleaning

In [6]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [7]:
# Encode the data

# Dummy encoding
df = pd.get_dummies(df, columns=['home_ownership', 'verification_status', 'next_pymnt_d'])

# Create the LabelEncoder instance
le = LabelEncoder()
# pymnt_plan column
le.fit(df["pymnt_plan"])
df["pymnt_plan"] = le.transform(df["pymnt_plan"])

# Encoding initial_list_status column
le.fit(df["initial_list_status"])
df["initial_list_status"] = le.transform(df["initial_list_status"])

# Encoding application_type column
le.fit(df["application_type"])
df["application_type"] = le.transform(df["application_type"])

# Encoding hardship_flag column
le.fit(df["hardship_flag"])
df["hardship_flag"] = le.transform(df["hardship_flag"])

# Encoding debt_settlement_flag column
le.fit(df["debt_settlement_flag"])
df["debt_settlement_flag"] = le.transform(df["debt_settlement_flag"])

# Drop the date column
df.drop(labels=['issue_d'], axis=1, inplace=True)
df.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,open_acc,...,debt_settlement_flag,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019
0,10500.0,0.1719,375.35,66000.0,low_risk,0,27.24,0.0,0.0,8.0,...,0,0,0,0,1,0,1,0,0,1
1,25000.0,0.2000,929.09,105000.0,low_risk,0,20.23,0.0,0.0,17.0,...,0,0,1,0,0,0,0,1,0,1
2,20000.0,0.2000,529.88,56000.0,low_risk,0,24.26,0.0,0.0,8.0,...,0,0,1,0,0,0,0,1,0,1
3,10000.0,0.1640,353.55,92000.0,low_risk,0,31.44,0.0,1.0,10.0,...,0,0,0,0,1,0,0,1,0,1
4,22000.0,0.1474,520.39,52000.0,low_risk,0,18.76,0.0,1.0,14.0,...,0,0,1,0,0,1,0,0,0,1

## Split the Data into Training and Testing

In [8]:
# Create our features
X = df.drop(columns='loan_status')

# Create our target
y = df['loan_status']
#y = pd.DataFrame({'loan status':yy})

In [9]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,debt_settlement_flag,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,16677.594562,0.127718,480.652863,8.821371e+04,0.0,21.778153,0.217766,0.497697,12.587340,0.126030,...,0.0,0.009285,0.526309,0.106747,0.357659,0.478007,0.373992,0.148001,0.383161,0.616839
std,10277.348590,0.048130,288.062432,1.155800e+05,0.0,20.199244,0.718367,0.758122,6.022869,0.336797,...,0.0,0.095914,0.499311,0.308793,0.479314,0.499520,0.483865,0.355104,0.486161,0.486161
min,1000.000000,0.060000,30.890000,4.000000e+01,0.0,0.000000,0.000000,0.000000,2.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9000.000000,0.088100,265.730000,5.000000e+04,0.0,13.890000,0.000000,0.000000,8.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,15000.000000,0.118000,404.560000,7.300000e+04,0.0,19.760000,0.000000,0.000000,11.000000,0.000000,...,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,24000.000000,0.155700,648.100000,1.040000e+05,0.0,26.660000,0.000000,1.000000,16.000000,0.000000,...,0.0,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,40000.000000,0.308400,1676.230000,8.797500e+06,0.0,999.000000,18.000000,5.000000,72.000000,4.000000,...,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [11]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)
X_train.shape

(51612, 90)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [12]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [13]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
data_scaler.fit(X_train)

StandardScaler()

In [14]:
# Scale the training and testing data
X_train = data_scaler.transform(X_train)
X_test = data_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [15]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
brf.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [16]:
# Calculated the balanced accuracy score
y_pred = brf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.699279596746943

In [17]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"]
)

display(cm_df)

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   50                  42
Actual Low Risk                  2480               14633

In [18]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred, digits=5))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk    0.01976   0.54348   0.85508   0.03814   0.68170   0.45024        92
   low_risk    0.99714   0.85508   0.54348   0.92066   0.68170   0.47920     17113

avg / total    0.99191   0.85341   0.54514   0.91594   0.68170   0.47904     17205

In [19]:
# List the features sorted in descending order by feature importance
importances = brf.feature_importances_
sorted(zip(importances, X.columns), reverse=True)

[(0.07072338254204659, 'last_pymnt_amnt'),
 (0.06965655884581433, 'total_rec_prncp'),
 (0.05773421268467116, 'total_pymnt_inv'),
 (0.056513488460141655, 'total_pymnt'),
 (0.05037414064917492, 'total_rec_int'),
 (0.027593087461120925, 'int_rate'),
 (0.02068910344622258, 'dti'),
 (0.018660030235146344, 'mo_sin_old_rev_tl_op'),
 (0.017911624083260094, 'max_bal_bc'),
 (0.01760733704412738, 'annual_inc'),
 (0.01675095517941912, 'bc_util'),
 (0.016134262473500145, 'mo_sin_old_il_acct'),
 (0.015895703132011732, 'total_rev_hi_lim'),
 (0.01581900822462686, 'out_prncp_inv'),
 (0.015740906301961528, 'mths_since_recent_inq'),
 (0.01560067975073092, 'total_bc_limit'),
 (0.015534345506065576, 'revol_bal'),
 (0.01531162938828252, 'avg_cur_bal'),
 (0.014943917607213072, 'tot_hi_cred_lim'),
 (0.014936810113464358, 'bc_open_to_buy'),
 (0.014675780295679732, 'out_prncp'),
 (0.014264173693367205, 'installment'),
 (0.013613107063699642, 'mths_since_rcnt_il'),
 (0.013492713083808417, 'tot_cur_bal'),
 (0.013379645024914224, 'all_util'),
 (0.013167844707451408, 'total_acc'),
 (0.012917810379926306, 'total_bal_il'),
 (0.01282353956136373, 'num_il_tl'),
 (0.012248704498884481, 'total_rec_late_fee'),
 (0.012138824918320214, 'total_il_high_credit_limit'),
 (0.012031682396146787, 'il_util'),
 (0.011700903591963694, 'total_bal_ex_mort'),
 (0.011620178875745008, 'num_sats'),
 (0.011581664192734523, 'inq_last_12m'),
 (0.010988180435170853, 'mths_since_recent_bc'),
 (0.010899032105945667, 'mo_sin_rcnt_tl'),
 (0.010636481898596319, 'num_rev_accts'),
 (0.010596848552885837, 'num_bc_tl'),
 (0.010533319480156147, 'mo_sin_rcnt_rev_tl_op'),
 (0.010120720544218025, 'inq_last_6mths'),
 (0.010111648534758988, 'loan_amnt'),
 (0.010013605327333239, 'num_actv_bc_tl'),
 (0.009732576207981323, 'num_actv_rev_tl'),
 (0.009332518805030414, 'inq_fi'),
 (0.009192953335351096, 'num_rev_tl_bal_gt_0'),
 (0.008973252799150531, 'open_il_24m'),
 (0.00890366557762552, 'acc_open_past_24mths'),
 (0.008856295005077746, 'pct_tl_nvr_dlq'),
 (0.008581964781181811, 'open_acc'),
 (0.00791111409972576, 'num_bc_sats'),
 (0.007679272081049544, 'num_op_rev_tl'),
 (0.007382933195066536, 'num_tl_op_past_12m'),
 (0.007198919809068388, 'total_cu_tl'),
 (0.0069681010648795835, 'percent_bc_gt_75'),
 (0.006525850229844044, 'open_rv_24m'),
 (0.006259771126243752, 'mort_acc'),
 (0.005813768814246292, 'open_act_il'),
 (0.005328635260153157, 'delinq_2yrs'),
 (0.005083669106848006, 'open_acc_6m'),
 (0.004648643911193616, 'open_rv_12m'),
 (0.004066821653787306, 'next_pymnt_d_Apr-2019'),
 (0.003917221008698818, 'open_il_12m'),
 (0.0036918437205689086, 'next_pymnt_d_May-2019'),
 (0.0034083537614366536, 'verification_status_Verified'),
 (0.0028601771162217824, 'num_accts_ever_120_pd'),
 (0.0027229312706144463, 'verification_status_Not Verified'),
 (0.0026400505242415557, 'tot_coll_amt'),
 (0.0022446445023409736, 'home_ownership_OWN'),
 (0.0019179396782301053, 'verification_status_Source Verified'),
 (0.0017228191850432997, 'pub_rec'),
 (0.0017156229864628344, 'pub_rec_bankruptcies'),
 (0.0016824457357371419, 'initial_list_status'),
 (0.0015838814566931077, 'home_ownership_MORTGAGE'),
 (0.0014042706212304024, 'home_ownership_RENT'),
 (0.0009734701422146728, 'num_tl_90g_dpd_24m'),
 (0.0007361429170552716, 'application_type'),
 (0.00023607391585110115, 'chargeoff_within_12_mths'),
 (0.00022759751375777196, 'home_ownership_ANY'),
 (0.00018619478802455095, 'collections_12_mths_ex_med'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [20]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier
m = EasyEnsembleClassifier(n_estimators=100,random_state=1)
m.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [21]:
# Calculated the balanced accuracy score
y_pred = m.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7041903688779697

In [22]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"]
)

display(cm_df)

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   57                  35
Actual Low Risk                  3614               13499

In [23]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred, digits=5))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk    0.01553   0.61957   0.78882   0.03029   0.69909   0.48045        92
   low_risk    0.99741   0.78882   0.61957   0.88093   0.69909   0.49699     17113

avg / total    0.99216   0.78791   0.62047   0.87639   0.69909   0.49691     17205

### Final Questions

1. Which model had the best balanced accuracy score?

    YOUR ANSWER HERE.

2. Which model had the best recall score?

    YOUR ANSWER HERE.

3. Which model had the best geometric mean score?

    YOUR ANSWER HERE.

4. What are the top three features?

    YOUR ANSWER HERE.